include DefinesPG.mk

default: gm_dense_phoenix.o mm_dense_phoenix.o

%.o: %.cpp
	$(CXX) -fpermissive $(CFLAGS) -c $< -o $@ -I$(PX_HOME)/$(INC_DIR)

%: %.o
	@mkdir -p $(HOME)/bin/$(@D)
	$(CXX) -fpermissive $(CFLAGS) -o $(HOME)/bin/$@ $@.o $(LIBS) -l$(PX_HOME)/lib/lphoenix


