include DefinesPG.mk

default: gm_dense_phoenix mm_dense_phoenix

%.o: %.cpp
	$(CXX) -fpermissive $(CFLAGS) -c $< -o $@ -I$(PX_HOME)/$(INC_DIR)

%: %.o
	@mkdir -p bin/$(@D)
	$(CXX) -fpermissive $(CFLAGS) -o bin/$@ $@.o $(LIBS)


